# Generated by Django 5.1 on 2024-08-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0002_user_phone_number_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
