# Generated by Django 5.1 on 2024-08-10 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0006_tests_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activate',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activate',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
