# Generated by Django 5.1 on 2024-08-10 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0010_remove_activate_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activate',
            name='start_date',
            field=models.DateTimeField(default=datetime.date(2024, 8, 10)),
            preserve_default=False,
        ),
    ]
