# Generated by Django 5.1 on 2024-08-10 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0011_activate_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activate',
            name='end_date',
            field=models.DateTimeField(default=datetime.date),
        ),
        migrations.AlterField(
            model_name='activate',
            name='start_date',
            field=models.DateTimeField(default=datetime.date),
        ),
    ]
