# Generated by Django 5.1 on 2024-08-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0014_alter_activate_end_date_alter_activate_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activate',
            name='end_date',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='activate',
            name='start_date',
            field=models.CharField(max_length=25),
        ),
    ]
