# Generated by Django 5.1 on 2024-08-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0020_remove_activate_end_date_remove_activate_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='activate',
            name='end_date',
            field=models.CharField(default=0, max_length=25),
        ),
        migrations.AddField(
            model_name='activate',
            name='start_date',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
