# Generated by Django 5.1 on 2024-08-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0022_remove_activate_end_date_remove_activate_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activate',
            name='id_theme',
        ),
    ]
