# Generated by Django 5.1 on 2024-08-10 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0028_alter_activate_id_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activate',
            name='date_end',
            field=models.DateField(default=datetime.date(2024, 8, 10)),
        ),
        migrations.AlterField(
            model_name='activate',
            name='date_start',
            field=models.DateField(default=datetime.date(2024, 8, 10)),
        ),
    ]
