# Generated by Django 5.1 on 2024-08-10 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0029_alter_activate_date_end_alter_activate_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activate',
            name='date_end',
            field=models.DateField(default=datetime.datetime(2024, 8, 10, 13, 43, 39, 936590)),
        ),
        migrations.AlterField(
            model_name='activate',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2024, 8, 10, 13, 43, 39, 936590)),
        ),
    ]
