# Generated by Django 5.1 on 2024-08-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0031_alter_activate_date_end_alter_activate_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activate',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='activate',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='is_true',
        ),
    ]
