# Generated by Django 5.1 on 2024-08-10 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0034_activate_date_end_activate_date_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activate',
            name='id_theme',
        ),
        migrations.AddField(
            model_name='activate',
            name='id_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system_test_app.tests'),
            preserve_default=False,
        ),
    ]
