# Generated by Django 5.1 on 2024-08-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0035_remove_activate_id_theme_activate_id_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activate',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activate',
            name='date_start',
            field=models.DateField(),
        ),
    ]
