# Generated by Django 5.1 on 2024-08-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0036_alter_activate_date_end_alter_activate_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activate',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activate',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
