# Generated by Django 5.1 on 2024-08-12 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_test_app', '0037_alter_activate_date_end_alter_activate_date_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
        migrations.RenameModel(
            old_name='Tests',
            new_name='Test',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('is_true', models.BooleanField(default=False)),
                ('tests_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_test_app.test')),
            ],
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
